name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set Playwright Execution Permissions
        run: chmod +x node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Generate Authentication Token
        run: npx playwright test tests/api/auth.test.ts

      - name: Run API Tests
        run: npx playwright test tests/api