name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ✅ Create .env file manually (Ensure these values are correct!)
      - name: Create .env file
        run: |
          echo "BASE_URL=https://stage.anaconda.com/api" >> .env
          echo "API_USERNAME=usamamanan23@gmail.com" >> .env
          echo "API_PASSWORD=Usama12345" >> .env
        shell: bash

      # ✅ Verify .env File Content
      - name: Verify .env File
        run: cat .env  

      # ✅ Install dependencies with a clean setup
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      # ✅ Set permissions for Playwright execution
      - name: Set Playwright Execution Permissions
        run: chmod +x node_modules/.bin/playwright

      # ✅ Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ✅ Run Authentication Test (Get Auth Token)
      - name: Generate Authentication Token
        run: npx playwright test tests/api/auth.test.ts

      # ✅ Verify that token.json file is updated correctly
      - name: Check Token File
        run: cat config/token.json

      # ✅ Run API Tests Only If Auth Token is Available
      - name: Run API Tests
        run: npx playwright test tests/api